import type {
  PatientProfile,
  LanguageOption,
  ConsentAuthorization,
  AccessAuditLog,
  ExtractedMedication,
} from "./types";

export const INDIC_LANGUAGES: LanguageOption[] = [
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "HI" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "TA" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "TE" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "BN" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "MR" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "KN" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "ML" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "GU" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "PA" },
  { code: "od", name: "Odia", nativeName: "ଓଡ଼ିଆ", flag: "OD" },
  { code: "en", name: "English", nativeName: "English (India)", flag: "EN" },
];

const KAMALA_CONSENTS: ConsentAuthorization[] = [
  {
    id: "con-1",
    granteeName: "Dr. A. Rajan (MD, General Medicine)",
    granteeType: "Doctor",
    purpose: "Routine OPD Consultation & Prescription Reconciliation",
    dataCategories: ["All History", "Active Medications", "Lab Reports"],
    accessLevel: "Full Care Access",
    validFrom: "2026-08-24 09:00",
    validTill: "2026-08-24 21:00",
    status: "Active",
  },
  {
    id: "con-2",
    granteeName: "Apollo Pharmacy #419",
    granteeType: "Pharmacy",
    purpose: "Record Medication Dispensation via QR",
    dataCategories: ["Prescription Write-Only"],
    accessLevel: "Write-Only (Dispensation)",
    validFrom: "2026-08-10 11:30",
    validTill: "2026-08-10 12:30",
    status: "Expired",
  },
  {
    id: "con-3",
    granteeName: "Thyrocare Central Diagnostic Laboratory",
    granteeType: "Diagnostic Lab",
    purpose: "Publish Verified FHIR Lab Observations",
    dataCategories: ["Lab Reports"],
    accessLevel: "Write-Only (Dispensation)",
    validFrom: "2026-07-22 08:00",
    validTill: "2026-07-22 20:00",
    status: "Expired",
  },
];

const KAMALA_AUDIT_LOGS: AccessAuditLog[] = [
  {
    id: "aud-1",
    timestamp: "2026-08-24 18:28:10",
    accessorName: "Dr. A. Rajan (MD)",
    accessorRole: "Treating Physician",
    facility: "District Hospital Tirunelveli",
    action: "Read Case Summary",
    dataAccessed: "60-Second Narrative HPI, Sulfa Allergy, Duplicate Meds",
    ipLocation: "Hospital LAN - Room 104 (IP: 10.24.1.104)",
  },
  {
    id: "aud-2",
    timestamp: "2026-08-24 18:22:04",
    accessorName: "TalkRx Intake Kiosk #2",
    accessorRole: "Patient Kiosk Terminal",
    facility: "District Hospital Tirunelveli",
    action: "Viewed Full Timeline",
    dataAccessed: "Patient Pre-fill Verification for Returning Patient",
    ipLocation: "OPD Waiting Hall 1 (IP: 10.24.1.202)",
  },
  {
    id: "aud-3",
    timestamp: "2026-08-10 11:45:22",
    accessorName: "Apollo Pharmacy Pharmacist",
    accessorRole: "Licensed Pharmacist #TN-9812",
    facility: "Apollo Pharmacy, Town Branch",
    action: "Appended Dispensation QR",
    dataAccessed: "Appended Metformin 500mg (Batch #AP2918) dispensation event",
    ipLocation: "Apollo POS Gateway (IP: 192.168.4.12)",
  },
];

export const MOCK_PATIENTS: PatientProfile[] = [
  {
    id: "pat-kamala-01",
    serialNumber: "10234501",
    createdAt: "2025-11-02 09:12",
    conditions: [],
    selfAssessments: [],
    doctorRecords: [],
    consents: KAMALA_CONSENTS,
    auditLog: KAMALA_AUDIT_LOGS,
    abhaId: "91-8274-1928-3847",
    abhaAddress: "kamala.sundaram@abdm",
    name: "Kamala Sundaram",
    age: 58,
    gender: "Female",
    phone: "+91 98401 23456",
    bloodGroup: "B+",
    preferredLanguage: "ta",
    isReturningPatient: true,
    tokenNumber: "TK-104",
    department: "General Medicine / Endocrinology",
    hospitalName: "District Hospital Tirunelveli",
    queueStatus: "case-completed",
    redFlagAlerts: [],
    allergies: ["Sulfa Drugs (Sulfonamides) - Severe Angioedema (2022)"],
    activeMedications: [
      {
        id: "med-1",
        rawText: "Tab. Metformin 500mg BD",
        standardMolecule: "Metformin Hydrochloride",
        brandName: "Glycomet 500",
        dosage: "500 mg",
        frequency: "Twice daily (after meals)",
        duration: "Chronic (Ongoing)",
        confidence: 0.98,
        confirmedByPatient: true,
        status: "active",
        source: "doctor-prescribed",
        prescribedBy: "Dr. A. Rajan (MD)",
        dispensedBy: "Apollo Pharmacy, Town Branch",
        dispensedAt: "2026-08-10",
      },
      {
        id: "med-2",
        rawText: "Tab. Telmisartan 40mg OD",
        standardMolecule: "Telmisartan",
        brandName: "Telma 40",
        dosage: "40 mg",
        frequency: "Once daily (morning)",
        duration: "Chronic (Ongoing)",
        confidence: 0.95,
        confirmedByPatient: true,
        status: "active",
        source: "pharmacy-dispensed",
        prescribedBy: "Dr. S. Meenakshi (PHC)",
        dispensedBy: "MedPlus Tirunelveli",
        dispensedAt: "2026-08-01",
      },
      {
        id: "med-3",
        rawText: "Tab. Glimepiride 1mg OD (Duplicate Risk Detected)",
        standardMolecule: "Glimepiride",
        brandName: "Amaryl 1",
        dosage: "1 mg",
        frequency: "Once daily",
        duration: "30 days",
        confidence: 0.92,
        confirmedByPatient: true,
        status: "active",
        source: "document-extracted",
        notes: "Prescribed at private clinic 2 weeks ago; overlaps with existing sulfonylurea class alert!",
      },
    ],
    structuredSummary: {
      chiefComplaint: "Bilateral burning knee pain and increased fatigue",
      duration: "3 weeks, worsening since 5 days",
      hpiNarrative:
        "58-year-old female with known Type 2 Diabetes Mellitus (8 yrs) and Systemic Hypertension (5 yrs) presents with gradual onset bilateral knee joint aching and burning dysesthesia. Pain is worse upon standing and climbing stairs, partially relieved by rest. Patient reports code-mixed Tamil symptoms: 'kaal romba eriyudhu, nadakka mudiyala'. Denies fever, chest tightness, or urinary burning. System captures 7 scanned historical prescriptions, highlights duplicate antidiabetic therapy, and flags documented Sulfa allergy prominently.",
      painCharacteristics: {
        site: "Bilateral Knees (Right > Left)",
        character: "Dull aching with neuropathic burning feet",
        severity: 6,
        aggravatingFactors: ["Prolonged walking", "Stair climbing"],
        relievingFactors: ["Rest", "Warm fomentation"],
      },
      pertinentPositives: [
        "Bilateral knee pain 3 weeks",
        "Burning feet sensation (Diabetic peripheral neuropathy suspicion)",
        "Post-prandial heaviness",
        "Documented Sulfa allergy in 2022",
      ],
      pertinentNegatives: [
        "No chest pain or dyspnoea",
        "No joint swelling or morning stiffness > 30 mins",
        "No syncope or palpitations",
        "No fever or calf swelling",
      ],
      redFlagsDetected: [],
      allergies: [
        {
          allergen: "Sulfonamides / Sulfa Derivatives",
          reaction: "Facial edema, wheezing, and urticaria",
          severity: "Life-Threatening",
        },
      ],
      currentMedications: [],
      pastMedicalHistory: ["Type 2 Diabetes Mellitus (2018)", "Hypertension (2021)"],
      pastSurgicalHistory: ["Tubectomy (1998)"],
      familyHistory: ["Father: T2DM, Stroke at age 68", "Mother: Hypertension"],
      lifestyle: {
        smoking: "Non-smoker",
        alcohol: "Nil",
        diet: "Vegetarian (High carbohydrate, low protein)",
        sleep: "Disturbed due to nocturnal burning feet (5 hrs/night)",
      },
      reviewOfSystems: {
        Cardiovascular: "No angina, orthopnoea, or PND",
        Endocrine: "Polyuria present at night (2-3 times), mild polydipsia",
        Musculoskeletal: "Crepitus bilateral knees, no joint effusion",
        Neurological: "Bilateral symmetrical glove-and-stocking paresthesia",
      },
      generatedAt: "2026-08-24 18:20",
      intakeDurationSeconds: 412,
    },
    timeline: [
      {
        id: "tl-1",
        date: "2026-08-24",
        time: "18:20",
        title: "AI Multimodal Case-Taking Completed",
        subtitle: "District Hospital OPD Kiosk #2",
        category: "case-taking",
        source: "patient-reported",
        sourceEntity: "TalkRx Kiosk Engine v2.4",
        facility: "District Hospital Tirunelveli",
        description: "Patient completed 412-second intake in Tamil with touch-assisted body-map. 48 structured points extracted.",
        tags: ["Tamil ASR", "SOAP Generated", "Sulfa Allergy Flagged"],
      },
      {
        id: "tl-2",
        date: "2026-08-10",
        time: "11:45",
        title: "Pharmacy Dispensation Recorded (Closed Loop)",
        subtitle: "Apollo Pharmacy, Town Branch",
        category: "dispensation",
        source: "pharmacy-dispensed",
        sourceEntity: "Apollo Pharmacy POS Integration",
        facility: "Apollo Pharmacy #419",
        description: "Dispensed Metformin 500mg (60 tabs) and Telmisartan 40mg (30 tabs) via ABHA Consent Token #CT-8891.",
        tags: ["Dispensed vs Prescribed Match", "Batch #AP2918"],
      },
      {
        id: "tl-3",
        date: "2026-07-22",
        time: "10:15",
        title: "Laboratory Panel (HbA1c & Lipid Profile)",
        subtitle: "Thyrocare Tirunelveli Central Lab",
        category: "lab",
        source: "lab-verified",
        sourceEntity: "Thyrocare LOINC Bridge",
        facility: "Thyrocare Central Diagnostics",
        description: "HbA1c: 8.4% (Elevated), Fasting Glucose: 164 mg/dL, Serum Creatinine: 0.9 mg/dL. LOINC mapped.",
        tags: ["HbA1c 8.4%", "LOINC: 4548-4"],
      },
      {
        id: "tl-4",
        date: "2026-05-14",
        time: "16:30",
        title: "Handwritten Prescription Digitized",
        subtitle: "Dr. S. Meenakshi (PHC)",
        category: "document",
        source: "document-extracted",
        sourceEntity: "TalkRx Document Vision AI",
        facility: "Government Primary Health Centre",
        description: "Prescription OCR extracted Telmisartan 40mg OD and recommended lifestyle diet modification.",
        tags: ["Prescription OCR", "98% Confidence"],
      },
      {
        id: "tl-5",
        date: "2022-11-04",
        time: "14:10",
        title: "Adverse Drug Reaction Recorded (Sulfa Allergy)",
        subtitle: "Tirunelveli Medical College Hospital",
        category: "consultation",
        source: "doctor-prescribed",
        sourceEntity: "Hospital HIS / ABDM",
        doctorName: "Dr. K. Balaji (MD)",
        facility: "Tirunelveli Medical College Hospital",
        description: "Patient developed acute facial angioedema after Co-trimoxazole. Hard allergy warning attached to ABHA profile.",
        tags: ["Allergy Intolerance", "High Severity"],
      },
    ],
    documents: [
      {
        id: "doc-1",
        title: "OPD Handwritten Prescription - Dr. A. Rajan",
        category: "prescription",
        date: "2026-08-10",
        facility: "District Hospital Tirunelveli",
        doctorName: "Dr. A. Rajan (MD)",
        ocrConfidence: 0.96,
        extractedMedicines: [],
        extractedLabs: [],
        extractedDiagnoses: ["Type 2 Diabetes Mellitus", "Bilateral Knee Osteoarthritis Grade 2"],
        rawText: "Rx: Tab Glycomet 500 BD x 1 mo, Tab Telma 40 OD, Cap Cal-D3 weekly. Review in 4 weeks with FBS/PPBS.",
        verified: true,
      },
      {
        id: "doc-2",
        title: "Diagnostic Lab Report - Glycated Hemoglobin & Renal Panel",
        category: "lab_report",
        date: "2026-07-22",
        facility: "Thyrocare Central Diagnostics",
        ocrConfidence: 0.99,
        extractedMedicines: [],
        extractedLabs: [
          {
            id: "lab-1",
            parameter: "HbA1c",
            value: "8.4",
            unit: "%",
            referenceRange: "< 5.7 (Normal), > 6.5 (Diabetes)",
            isAbnormal: true,
            loincCode: "4548-4",
            sourceDoc: "doc-2",
            date: "2026-07-22",
          },
          {
            id: "lab-2",
            parameter: "Fasting Blood Sugar",
            value: "164",
            unit: "mg/dL",
            referenceRange: "70 - 100",
            isAbnormal: true,
            loincCode: "1558-6",
            sourceDoc: "doc-2",
            date: "2026-07-22",
          },
          {
            id: "lab-3",
            parameter: "Serum Creatinine",
            value: "0.9",
            unit: "mg/dL",
            referenceRange: "0.6 - 1.2",
            isAbnormal: false,
            loincCode: "2160-0",
            sourceDoc: "doc-2",
            date: "2026-07-22",
          },
        ],
        extractedDiagnoses: ["Suboptimally Controlled T2DM"],
        rawText: "Thyrocare Lab Report: HbA1c 8.4%, Estimated Avg Glucose 194 mg/dL. Fasting Glucose 164 mg/dL.",
        verified: true,
      },
    ],
  },
  {
    id: "pat-suresh-02",
    serialNumber: "20239817",
    createdAt: "2026-08-24 18:20",
    conditions: [],
    selfAssessments: [],
    doctorRecords: [],
    consents: [],
    auditLog: [],
    abhaId: "91-4491-0021-9982",
    abhaAddress: "suresh.kumar47@abdm",
    name: "Suresh Kumar",
    age: 47,
    gender: "Male",
    phone: "+91 94432 99881",
    bloodGroup: "O+",
    preferredLanguage: "hi",
    isReturningPatient: false,
    tokenNumber: "TK-108 [PRIORITY RED-FLAG]",
    department: "General Medicine / Emergency Triage",
    hospitalName: "District Hospital Tirunelveli",
    queueStatus: "triage-alert",
    redFlagAlerts: [],
    allergies: ["No known drug allergies (NKDA)"],
    activeMedications: [
      {
        id: "med-s-1",
        rawText: "Cap. Omeprazole 20mg (Self-medicated for 'gas trouble')",
        standardMolecule: "Omeprazole",
        brandName: "Omez",
        dosage: "20 mg",
        frequency: "Once daily",
        duration: "2 days",
        confidence: 0.99,
        confirmedByPatient: true,
        status: "active",
        source: "patient-reported",
        notes: "Patient took antacid mistaking angina for indigestion.",
      },
    ],
    structuredSummary: {
      chiefComplaint: "Central crushing chest heaviness radiating to left arm with diaphoresis",
      duration: "45 minutes, progressive",
      hpiNarrative:
        "47-year-old male presents with acute central retrosternal pressure described as a heavy weight, with radiation to the left shoulder and medial arm. Onset 45 minutes ago while climbing bus steps. Associated with cold sweating and shortness of breath at rest. Patient took antacid tablet at home with zero relief. DETERMINISTIC RULE ENGINE TRIGGERED: Acute Coronary Syndrome (ACS) criteria met. Automatic priority escalation sent to Triage Desk & Duty Medical Officer.",
      painCharacteristics: {
        site: "Retrosternal / Precordial",
        radiation: "Left shoulder, left inner arm, and jaw",
        character: "Crushing tightness / Band-like pressure",
        severity: 9,
        aggravatingFactors: ["Physical exertion", "Deep breathing"],
        relievingFactors: ["None"],
      },
      pertinentPositives: [
        "Retrosternal crushing pain radiating to left arm",
        "Diaphoresis (profuse sweating)",
        "Dyspnoea at rest",
        "Smoker: 15 pack-years",
      ],
      pertinentNegatives: [
        "No pleuritic pain component",
        "No relief with antacids",
        "No fever or productive cough",
      ],
      redFlagsDetected: [
        {
          id: "rf-101",
          category: "cardiac",
          severity: "critical",
          matchedRule: "RULE_ACS_01: Central chest pain + radiation to left arm + diaphoresis / dyspnoea",
          patientStatement: "chhati me bahut bhaari pan hai, baaye haath me dard jaa raha hai aur bahut paseena aa raha hai",
          timestamp: "2026-08-24 18:26",
          escalatedTo: "Triage Station 1 & Emergency Room Nurse Device",
          status: "active",
          actionRequired: "Immediate 12-lead ECG, Oxygen, IV access, and stat physician bedside review.",
        },
      ],
      allergies: [],
      currentMedications: [],
      pastMedicalHistory: ["Smoker (15 cigarettes/day for 20 years)"],
      pastSurgicalHistory: [],
      familyHistory: ["Elder brother suffered MI at age 49"],
      lifestyle: {
        smoking: "Active Smoker (20 yrs)",
        alcohol: "Occasional social",
        diet: "Non-vegetarian",
        sleep: "6 hours/night",
      },
      reviewOfSystems: {
        Cardiovascular: "Acute chest heaviness, palpitation, diaphoresis",
        Respiratory: "Dyspnoea on mild effort",
      },
      generatedAt: "2026-08-24 18:26",
      intakeDurationSeconds: 184,
    },
    timeline: [
      {
        id: "tl-s-1",
        date: "2026-08-24",
        time: "18:26",
        title: "CRITICAL RED-FLAG ALERT TRIGGERED",
        subtitle: "TalkRx Deterministic Safety Engine",
        category: "triage",
        source: "patient-reported",
        sourceEntity: "Emergency Rule Engine ACS_01",
        facility: "District Hospital Emergency Triage",
        description: "Patient diverted from routine OPD queue to Red Triage Bed #1. Duty nurse and on-call cardiologist notified.",
        tags: ["Cardiac Red Flag", "Immediate ECG Required"],
        isRedFlag: true,
      },
      {
        id: "tl-s-2",
        date: "2026-08-24",
        time: "18:23",
        title: "Multimodal Voice Intake Started",
        subtitle: "OPD Kiosk #1 (Hindi Speech)",
        category: "case-taking",
        source: "patient-reported",
        sourceEntity: "TalkRx Speech AI",
        facility: "District Hospital Tirunelveli",
        description: "Patient identified chief complaint of severe chest discomfort. Question graph automatically branched to Cardiac line.",
        tags: ["Hindi ASR", "Cardiac Branch"],
      },
    ],
    documents: [],
  },
  {
    id: "pat-ramesh-03",
    serialNumber: "30248802",
    createdAt: "2026-01-14 10:05",
    conditions: [],
    selfAssessments: [],
    doctorRecords: [],
    consents: [],
    auditLog: [],
    abhaId: "91-1122-3344-5566",
    abhaAddress: "ramesh.vaidya@abdm",
    name: "Ramesh Sharma",
    age: 44,
    gender: "Male",
    phone: "+91 97721 44556",
    bloodGroup: "A+",
    preferredLanguage: "hi",
    isReturningPatient: false,
    tokenNumber: "AY-042",
    department: "Government Ayurvedic OPD (Kaya Chikitsa)",
    hospitalName: "National Institute of Ayurveda Hospital",
    queueStatus: "case-completed",
    redFlagAlerts: [],
    allergies: ["NKDA"],
    activeMedications: [
      {
        id: "med-r-1",
        rawText: "Avipattikar Churna 3g BD with lukewarm water",
        standardMolecule: "Avipattikar Churna (Ayurvedic Formulary of India)",
        brandName: "Dabur Avipattikar",
        dosage: "3 g",
        frequency: "Twice daily before food",
        duration: "15 days",
        confidence: 0.99,
        confirmedByPatient: true,
        status: "active",
        source: "ayush-assessed",
      },
    ],
    ayushData: {
      prakriti: {
        primaryDosha: "Pitta-Vata",
        scores: { vata: 35, pitta: 48, kapha: 17 },
        physicalTraits: "Medium build, warm flushed skin, prone to acidity, quick movement",
        psychologicalTraits: "Sharp intellect, impatient when hungry, irregular sleep cycles",
      },
      vikriti: {
        imbalancedDosha: "Pitta",
        currentDeviation: "Amlapitta with Vidagdha Ajirna (Hyperacidity with delayed gastric emptying)",
        namasteMorbidityCode: "AYU-MOR-0419: Amlapitta (Hyperacidity syndrome)",
        whoIcd11Tm2Code: "TM2-GA-084: Pittaja Grahani Disorder",
      },
      sara: { tissueQuality: "Madhyama (Medium)", dominantTissue: "Rakta & Meda" },
      samhanana: { build: "Moderate" },
      pramana: { anthropometry: "Proportionate" },
      satmya: { habituation: "Mixed (Predominantly pungent, sour, spicy foods)" },
      sattva: { mentalStrength: "Madhyama (Moderate)" },
      aharaShakti: { abhyavaharana: "High Appetite", jaranaShakti: "Sluggish" },
      vyayamaShakti: { exerciseCapacity: "Moderate" },
      vaya: { ageClassification: "Madhyama (Middle age)" },
      ashtavidha: {
        nadi: "Mandukagati (Pitta-dominant, rapid and bounding, 82 bpm)",
        mutra: "Peeta varna (Yellowish, burning sensation occasionally)",
        mala: "Vid-bandha alternating with loose stools, amadosha present",
        jihva: "Saama (White coated posterior tongue with red margins)",
        shabda: "Spashta (Clear voice)",
        sparsha: "Ushna (Warm extremities)",
        drik: "Raktanta (Mild conjunctival hyperemia)",
        akriti: "Madhyama (Medium frame)",
      },
      agni: "Tikshnagni (Intense)",
      koshtha: "Mridu (Soft)",
    },
    structuredSummary: {
      chiefComplaint: "Chronic heartburn, acid regurgitation, and postprandial epigastric fullness",
      duration: "6 months, aggravated in past 2 weeks",
      hpiNarrative:
        "44-year-old male software engineer presents with 6-month history of burning sensation in chest and throat (Tikta-Amla Udgara), especially 1-2 hours after meals and at bedtime. Full 10-fold Dashavidha Pariksha conducted via 14 minutes of waiting time: Pitta-dominant Vikriti with Saama Jihva and Tikshnagni. Coded against NAMASTE (AYU-MOR-0419) and WHO ICD-11 TM Module 2.",
      pertinentPositives: ["Acid regurgitation after oily food", "Coated tongue (Saama)", "Sleep disruption around 2 AM"],
      pertinentNegatives: ["No hematemesis or melena", "No dysphagia or unintentional weight loss"],
      redFlagsDetected: [],
      allergies: [],
      currentMedications: [],
      pastMedicalHistory: ["Recurrent dyspepsia since 2024"],
      pastSurgicalHistory: [],
      familyHistory: ["Father had peptic ulcer disease"],
      lifestyle: {
        smoking: "Non-smoker",
        alcohol: "Rare (1-2 times/year)",
        diet: "Spicy, irregular timings, late-night dinners",
        sleep: "Irregular (1 AM to 7 AM)",
      },
      reviewOfSystems: {
        Gastrointestinal: "Amlapitta, Vidagdha Ajirna, sour eructations",
      },
      generatedAt: "2026-08-24 17:50",
      intakeDurationSeconds: 610,
    },
    timeline: [
      {
        id: "tl-r-1",
        date: "2026-08-24",
        time: "17:50",
        title: "Dashavidha Pariksha Completed",
        subtitle: "Ayurvedic OPD Kiosk #3",
        category: "ayush",
        source: "ayush-assessed",
        sourceEntity: "TalkRx Dashavidha Engine",
        facility: "National Institute of Ayurveda Hospital",
        description: "Prakriti/Vikriti constitutional profile generated and mapped to NAMASTE AYU-MOR-0419.",
        tags: ["Pitta Vikriti", "NAMASTE Coded", "WHO ICD-11 TM-2"],
      },
    ],
    documents: [],
  },
];
